# -*- coding: utf-8 -*-

'''

Python says

A program that generates Verilog code and verify, build and load the code using APIO

Made by Julián Caro Linares

jcarolinares@gmail.com

CC-BY-SA

'''

#Python 3

#Libraries
import os
import subprocess
import time

#import apio #FIXME right now it's only work with Python 2, waiting for the fpga community mailing link response
#from apio.managers.scons import SCons
#from apio.managers.project import Project

#Template generator library
import em

#Variables
path="." #By the time the path it must be the root of the project. Apio needs that (Scons().verify doesn't have a path parameter)
fpgaboard="icezum"
pythonsays_memo="[PYTHON SAYS]: " #Keyword that defines the outputs generated by pythonsays


class VerilogBlock:
    #Parent class to create any verilog block or component
    template_name=""
    template_path="."
    output_file="output.v"
    argv=""

    def __init__ (self,template_name,argv,template_path,output_file):
        self.template_name=template_name
        self.argv=argv
        self.template_path=template_path
        self.output_file=output_file

    def generate(self):
        file = open(self.output_file, 'w')
        interpreter = em.Interpreter(output=file ,argv=str(self.argv))

        # Process an actual file (and output to stdout):
        interpreter.file(open(self.template_path+"/"+self.template_name))
        interpreter.shutdown() # this is important; see below

    #Apio implementation using subprocess commands
    def verify(self):
        subprocess.call('apio "verify"' ,shell=True)
    def build(self):
        subprocess.call('apio "build"' ,shell=True)
    def upload(self):
        subprocess.call('apio "upload"' ,shell=True)

class CounterBlock (VerilogBlock): #The VerilogBLock is a generic class that can create whatever you want, not need of derives functions, in this case a derived function should be useful to create some very commonly used blocks inside a robot, but not 100% neccessary
    N=20

    def __init__ (self,template_name,N,template_path):
        self.N=N
        super().__init__(template_name,template_path)


#Main execution
def main():

    test_counter=VerilogBlock("counter.em",20,".","counter.v")

    m_list=[5,10,15,20,25,30]

    for m in m_list:
        test_counter.argv=m

        test_counter.generate()
        test_counter.verify()
        test_counter.build()
        test_counter.upload()

        time.sleep(10)

    '''
    file_name="counter.v"

    file = open(file_name, 'w')

    m_list=[5,10,15,20,25,30]
    for m in m_list:
        print("Creando circuito con M: ",m)
        file = open(file_name, 'w')
        interpreter = em.Interpreter(output=file ,argv=str(m))

        # Process an actual file (and output to stdout):
        interpreter.file(open('counter.em'))
        interpreter.shutdown() # this is important; see below

        subprocess.call('apio "verify"' ,shell=True)
        subprocess.call('apio "build"' ,shell=True)
        subprocess.call('apio "upload"' ,shell=True)

        time.sleep(10);
        '''
if __name__ == "__main__":
 main()
